module.exports = function(grunt) {
  grunt.initConfig({
    cssmin:{
      minify:{
        files:{
          'public/css/fulldisplay.min.css':'public/css/fulldisplay.css',
          'public/css/parentdisplay.min.css':'public/css/parentdisplay.css',
          'public/v1.1/css/fulldisplay.min.css':'public/v1.1/css/fulldisplay.css'
        }
      }
    },
    uglify:{
      dist:{
        files:{
          'public/js/breadcrumb.min.js':'public/js/breadcrumb.js',
          'public/v1.1/js/breadcrumb.min.js':'public/v1.1/js/breadcrumb.js',
          'public/v1.1/js/category_archive.min.js':'public/v1.1/js/category_archive.js'
        }
      }
    }
  });
grunt.loadNpmTasks('grunt-contrib-uglify');
grunt.loadNpmTasks('grunt-contrib-cssmin');
grunt.registerTask('default',['cssmin','uglify']);
}
